import { Incident, SosRequest, Resource, EmergencyAlert, Shelter, ExternalDataSource, AuditLog, CityInfo, EmergencyHelp } from './types';

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: '104',
    title: 'Severe waterlogging and basement flooding in residential society',
    type: 'Flood',
    description: 'Ground floors and basements submerged under 4.5ft floodwaters. 23 residents isolated, elderly individuals require immediate evacuation by inflatable boats.',
    latitude: 23.0125,
    longitude: 72.5620,
    locationName: 'Paldi, Ahmedabad, Gujarat',
    severity: 'CRITICAL',
    status: 'IN PROGRESS',
    source: 'Citizen Report',
    verified: true,
    verifiedBy: 'Riya Sharma (Coordinator)',
    affectedPeople: 23,
    assignedResourceIds: ['res-amb-02', 'res-rescue-04'],
    assignedNgoId: 'ngo-redcross-01',
    assignedNgoName: 'Red Cross Disaster Relief Taskforce',
    ngoMissionStatus: 'ON_SITE',
    ngoInstructions: 'Deploy 2 inflatable rescue boats; evacuate 12 stranded residents and provide immediate hot meals.',
    ngoSitrep: 'Rescue boats launched; 14 people safely evacuated to relief shelter. Continuing secondary sweep.',
    timeline: [
      { id: 't1', time: '14:32', label: 'Reported', status: 'REPORTED', note: 'Multiple citizen SOS calls received from residential society' },
      { id: 't2', time: '14:35', label: 'Verified', status: 'VERIFIED', note: 'Ground police confirmed water level at 4.5 feet' },
      { id: 't3', time: '14:38', label: 'Assigned', status: 'ASSIGNED', note: 'Ambulance 02 and Rescue Team 4 dispatched' },
      { id: 't4', time: '14:45', label: 'In Progress', status: 'IN PROGRESS', note: 'Rescue boats launched; 14 people safely evacuated to relief camp' },
    ],
    evidenceUrl: '/images/evidence/paldi.jpg',
    createdAt: '2026-09-08T14:32:00Z',
    updatedAt: '2026-09-08T14:45:00Z',
  },
  {
    id: '105',
    title: 'Sabarmati Riverfront promenade water overflow breaching storm barriers',
    type: 'Flood',
    description: 'Sabarmati water level surpassed danger threshold (136ft). Water overflowing into lower promenade and adjoining arterial road.',
    latitude: 23.0450,
    longitude: 72.5780,
    locationName: 'Usmanpura Riverfront, Ahmedabad',
    severity: 'HIGH',
    status: 'ASSIGNED',
    source: 'Sensor Network',
    verified: true,
    verifiedBy: 'NDMA River Telemetry',
    affectedPeople: 45,
    assignedResourceIds: ['res-fire-03'],
    assignedNgoId: 'ngo-sevabharati-02',
    assignedNgoName: 'Seva Bharati Rescue Squad',
    ngoMissionStatus: 'DISPATCHED',
    ngoInstructions: 'Erect sandbag barriers and distribute clean drinking water to stranded commuters along lower promenade.',
    ngoSitrep: 'Water barriers in place; mobile tanker dispensing drinking water.',
    timeline: [
      { id: 't105-1', time: '14:15', label: 'Reported', status: 'REPORTED', note: 'Automated gauge triggered amber warning' },
      { id: 't105-2', time: '14:20', label: 'Verified', status: 'VERIFIED', note: 'Municipal engineer verified storm gate overflow' },
      { id: 't105-3', time: '14:30', label: 'Assigned', status: 'ASSIGNED', note: 'Dispatched to Seva Bharati Rescue Squad' },
    ],
    createdAt: '2026-09-08T14:15:00Z',
    updatedAt: '2026-09-08T14:30:00Z',
  },
  {
    id: '106',
    title: 'Old three-story residential structure partial wall collapse',
    type: 'Building Collapse',
    description: 'Heavy rain weakened foundation of old masonry building. Rear wall collapsed onto alley. 8 people inside require evacuation and safety perimeter.',
    latitude: 23.0200,
    longitude: 72.5700,
    locationName: 'Ellis Bridge, Ahmedabad',
    severity: 'CRITICAL',
    status: 'ASSIGNED',
    source: 'Emergency Call',
    verified: true,
    verifiedBy: 'Control Room Officer #4',
    affectedPeople: 8,
    assignedResourceIds: ['res-rescue-01'],
    assignedNgoId: 'ngo-doctors-03',
    assignedNgoName: 'Doctors For You Medical Corps',
    ngoMissionStatus: 'PENDING_ACKNOWLEDGEMENT',
    ngoInstructions: 'Urgent medical triage for collapsed building residents; prepare stretcher, neck braces, and splints.',
    timeline: [
      { id: 't106-1', time: '14:40', label: 'Reported', status: 'REPORTED', note: 'Emergency 112 caller reported structural sound and collapse' },
      { id: 't106-2', time: '14:44', label: 'Verified', status: 'VERIFIED', note: 'Local police unit on scene confirmed structural breach' },
      { id: 't106-3', time: '14:46', label: 'Assigned', status: 'ASSIGNED', note: 'Direct mission assigned to Doctors For You Medical Corps' },
    ],
    evidenceUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=600&q=80',
    createdAt: '2026-09-08T14:40:00Z',
    updatedAt: '2026-09-08T14:44:00Z',
  },
  {
    id: '107',
    title: 'Electrical substation short circuit & transformer fire in flooded zone',
    type: 'Fire',
    description: 'Submerged transformer at local power distribution node caught fire with electrical arcing. Power isolation required immediately before water discharge.',
    latitude: 23.0360,
    longitude: 72.5590,
    locationName: 'Navrangpura, Ahmedabad',
    severity: 'HIGH',
    status: 'ASSIGNED',
    source: 'Citizen Report',
    verified: true,
    verifiedBy: 'Riya Sharma (Coordinator)',
    affectedPeople: 15,
    assignedResourceIds: ['res-fire-01'],
    timeline: [
      { id: 't107-1', time: '14:22', label: 'Reported', status: 'REPORTED', note: 'Citizen submitted video evidence of transformer smoke' },
      { id: 't107-2', time: '14:25', label: 'Verified', status: 'VERIFIED', note: 'Power distribution board confirmed feeder trip' },
      { id: 't107-3', time: '14:28', label: 'Assigned', status: 'ASSIGNED', note: 'Fire Unit 01 en route with chemical extinguishing foam' },
    ],
    createdAt: '2026-09-08T14:22:00Z',
    updatedAt: '2026-09-08T14:28:00Z',
  },
  {
    id: '108',
    title: 'Akhbarnagar Underpass submerged with 2 stranded civilian vehicles',
    type: 'Flood',
    description: 'Water depth reached 5.2 feet inside underpass. Drivers abandoned cars and are on elevated embankment; barricading required.',
    latitude: 23.0610,
    longitude: 72.5680,
    locationName: 'Akhbarnagar Underpass, Ahmedabad',
    severity: 'MEDIUM',
    status: 'VERIFIED',
    source: 'Citizen Report',
    verified: true,
    verifiedBy: 'Traffic Command Center',
    affectedPeople: 4,
    assignedResourceIds: ['res-police-01'],
    timeline: [
      { id: 't108-1', time: '14:10', label: 'Reported', status: 'REPORTED', note: 'Citizen report with photo' },
      { id: 't108-2', time: '14:18', label: 'Verified', status: 'VERIFIED', note: 'Traffic police verified underpass closure' },
      { id: 't108-3', time: '14:22', label: 'Assigned', status: 'ASSIGNED', note: 'Police Patrol 01 dispatched for cordon' },
    ],
    createdAt: '2026-09-08T14:10:00Z',
    updatedAt: '2026-09-08T14:22:00Z',
  },
  {
    id: '109',
    title: 'Severe banyan tree fall blocking arterial access road to Civil Hospital',
    type: 'Road Accident',
    description: 'Unverified citizen report stating large fallen branch has completely choked northbound emergency access lane.',
    latitude: 23.0480,
    longitude: 72.6020,
    locationName: 'Asarwa Hospital Road, Ahmedabad',
    severity: 'MEDIUM',
    status: 'PENDING VERIFICATION',
    source: 'Citizen Report',
    verified: false,
    affectedPeople: 12,
    assignedResourceIds: [],
    timeline: [
      { id: 't109-1', time: '14:48', label: 'Reported', status: 'REPORTED', note: 'Citizen submission via mobile web app' },
      { id: 't109-2', time: '14:49', label: 'Pending Verification', status: 'PENDING VERIFICATION', note: 'Awaiting local beat officer validation' },
    ],
    createdAt: '2026-09-08T14:48:00Z',
    updatedAt: '2026-09-08T14:49:00Z',
  },
  {
    id: '110',
    title: 'Flash flooding in informal settlement near canal bank',
    type: 'Flood',
    description: 'Unverified community alert: Canal bank seepage flooding approx 40 low-lying shanties.',
    latitude: 22.9800,
    longitude: 72.6100,
    locationName: 'Vatva Canal Bank, Ahmedabad',
    severity: 'HIGH',
    status: 'REPORTED',
    source: 'Citizen Report',
    verified: false,
    affectedPeople: 60,
    assignedResourceIds: [],
    timeline: [
      { id: 't110-1', time: '14:52', label: 'Reported', status: 'REPORTED', note: 'Crowdsourced community broadcast' },
    ],
    createdAt: '2026-09-08T14:52:00Z',
    updatedAt: '2026-09-08T14:52:00Z',
  },
  {
    id: '111',
    title: 'Senior living facility ground floor inundated with rapid runoff',
    type: 'Flood',
    description: '34 elderly occupants on ground floor unable to navigate stairs. Medical support and specialized wheel-chair transfer required.',
    latitude: 23.1100,
    longitude: 72.5850,
    locationName: 'Chandkheda, Ahmedabad',
    severity: 'CRITICAL',
    status: 'IN PROGRESS',
    source: 'Official Agency',
    verified: true,
    verifiedBy: 'SDRF Commander Vyas',
    affectedPeople: 34,
    assignedResourceIds: ['res-rescue-02', 'res-amb-01'],
    assignedNgoId: 'ngo-goonj-04',
    assignedNgoName: 'Goonj Rapid Humanitarian Wing',
    ngoMissionStatus: 'ON_SITE',
    ngoInstructions: 'Deliver 50 emergency ration kits, dry food, and clean water to seniors in 1st floor shelter.',
    ngoSitrep: 'Food kits handed over to shelter in-charge. All 20 seniors provided fresh drinking water.',
    timeline: [
      { id: 't111-1', time: '14:05', label: 'Reported', status: 'REPORTED', note: 'Superintendent emergency call' },
      { id: 't111-2', time: '14:10', label: 'Verified', status: 'VERIFIED', note: 'Direct district magistrate escalation' },
      { id: 't111-3', time: '14:15', label: 'Assigned', status: 'ASSIGNED', note: 'Dispatched directly to Goonj Rapid Humanitarian Wing' },
      { id: 't111-4', time: '14:26', label: 'In Progress', status: 'IN PROGRESS', note: 'Evacuation underway; 20 seniors relocated to 1st floor shelter' },
    ],
    createdAt: '2026-09-08T14:05:00Z',
    updatedAt: '2026-09-08T14:26:00Z',
  },
  {
    id: '112',
    title: 'Storm drain blockage cleared and water receding on railway subway',
    type: 'Flood',
    description: 'Municipal suction pumps successfully cleared storm line; road open for light vehicular movement.',
    latitude: 22.9980,
    longitude: 72.6010,
    locationName: 'Maninagar Railway Underbridge',
    severity: 'LOW',
    status: 'RESOLVED',
    source: 'NGO Field Team',
    verified: true,
    verifiedBy: 'Municipal Ward Officer #7',
    affectedPeople: 0,
    assignedResourceIds: [],
    timeline: [
      { id: 't112-1', time: '13:00', label: 'Reported', status: 'REPORTED', note: 'Water stagnation reported' },
      { id: 't112-2', time: '13:30', label: 'Verified', status: 'VERIFIED', note: 'Municipal team assigned' },
      { id: 't112-3', time: '14:15', label: 'Resolved', status: 'RESOLVED', note: 'Pumping complete, traffic resumed' },
    ],
    createdAt: '2026-09-08T13:00:00Z',
    updatedAt: '2026-09-08T14:15:00Z',
    resolvedAt: '2026-09-08T14:15:00Z',
  },
];

export const INITIAL_SOS_REQUESTS: SosRequest[] = [
  {
    id: 'SOS-891',
    userId: 'usr-cit-101',
    userName: 'Arjun Patel',
    userPhone: '+91 98250 11234',
    incidentId: '104',
    latitude: 23.0135,
    longitude: 72.5610,
    locationName: 'Shivalik Park, Flat 201, Ahmedabad',
    disasterType: 'Flood',
    peopleCount: 5,
    description: 'Water entered building lobby and reached first floor stairs. 2 senior citizens need assistance. Power cut off.',
    status: 'NEW',
    createdAt: '2026-09-08T14:50:00Z',
  },
  {
    id: 'SOS-892',
    userId: 'usr-cit-102',
    userName: 'Neha Mehta',
    userPhone: '+91 94280 55678',
    incidentId: '111',
    latitude: 23.1090,
    longitude: 72.5840,
    locationName: 'Chandkheda Aastha Residency, Ahmedabad',
    disasterType: 'Flood',
    peopleCount: 4,
    description: 'Trapped on terrace with young children. Flood current too strong to walk outside.',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-08T14:38:00Z',
    acknowledgedAt: '2026-09-08T14:41:00Z',
  },
  {
    id: 'SOS-893',
    userId: 'usr-cit-103',
    userName: 'Ramesh Varma',
    userPhone: '+91 98980 99881',
    incidentId: '105',
    latitude: 23.0460,
    longitude: 72.5760,
    locationName: 'Usmanpura River Approach Road',
    disasterType: 'Flood',
    peopleCount: 3,
    description: 'Car stalled in rising water near promenade. Water at window level, 1 infant inside.',
    status: 'ASSIGNED',
    createdAt: '2026-09-08T14:25:00Z',
    acknowledgedAt: '2026-09-08T14:26:00Z',
    assignedTo: 'Fire Unit 03',
  },
  {
    id: 'SOS-894',
    userId: 'usr-cit-104',
    userName: 'Sunita Rao',
    userPhone: '+91 97120 33445',
    incidentId: '106',
    latitude: 23.0210,
    longitude: 72.5690,
    locationName: 'Ellis Bridge Old Wada, Ahmedabad',
    disasterType: 'Building Collapse',
    peopleCount: 2,
    description: 'Partial ceiling collapsed in kitchen, uncle suffered ankle fracture.',
    status: 'ASSIGNED',
    createdAt: '2026-09-08T14:42:00Z',
    acknowledgedAt: '2026-09-08T14:43:00Z',
    assignedTo: 'Rescue Team 01',
  },
  {
    id: 'SOS-895',
    userId: 'usr-cit-105',
    userName: 'Imran Khan',
    userPhone: '+91 99090 77112',
    latitude: 22.9810,
    longitude: 72.6090,
    locationName: 'Vatva Slum Quarters, Ahmedabad',
    disasterType: 'Flood',
    peopleCount: 6,
    description: 'Water at waist level. Small mud brick shelter starting to erode.',
    status: 'NEW',
    createdAt: '2026-09-08T14:55:00Z',
  },
];

export interface NgoOrganization {
  id: string;
  name: string;
  focus: string;
  contact: string;
  headquartersPoc: string;
  activeVolunteers: number;
  assignedMissionsCount: number;
  operationalZones: string[];
  headquartersZone: string;
  activeSquads: number;
  status: string;
  specializations: string[];
  phone: string;
  contactPoc: string;
}

export const NGO_ORGANIZATIONS: NgoOrganization[] = [
  {
    id: 'ngo-redcross-01',
    name: 'Red Cross Disaster Relief Taskforce',
    focus: 'Search, Evacuation & Rapid First Aid',
    contact: '+91 98250 90001',
    headquartersPoc: 'Dr. Anita Joshi (HQ Liaison)',
    activeVolunteers: 45,
    assignedMissionsCount: 1,
    operationalZones: ['Paldi', 'Navrangpura', 'Ellis Bridge'],
    headquartersZone: 'Paldi Command Wing',
    activeSquads: 6,
    status: 'DEPLOYED',
    specializations: ['Flood Evacuation', 'Emergency First-Aid', 'Rescue Boats'],
    phone: '+91 98250 90001',
    contactPoc: 'Dr. Anita Joshi'
  },
  {
    id: 'ngo-sevabharati-02',
    name: 'Seva Bharati Rescue Squad',
    focus: 'Flood Water Rescue & Community Sandbagging',
    contact: '+91 98250 90002',
    headquartersPoc: 'Mahesh Patel (Field Director)',
    activeVolunteers: 60,
    assignedMissionsCount: 1,
    operationalZones: ['Usmanpura', 'Riverfront West', 'Subhash Bridge'],
    headquartersZone: 'Riverfront Taskforce Camp',
    activeSquads: 8,
    status: 'DEPLOYED',
    specializations: ['Deep Water Rescue', 'Sandbagging', 'Victim Evacuation'],
    phone: '+91 98250 90002',
    contactPoc: 'Mahesh Patel'
  },
  {
    id: 'ngo-doctors-03',
    name: 'Doctors For You Medical Corps',
    focus: 'Emergency Trauma & Field Hospital Triage',
    contact: '+91 98250 90003',
    headquartersPoc: 'Dr. Rajesh Shah (Medical Chief)',
    activeVolunteers: 28,
    assignedMissionsCount: 1,
    operationalZones: ['Ellis Bridge', 'Civil Hospital Base', 'Paldi'],
    headquartersZone: 'Civil Hospital Trauma Base',
    activeSquads: 4,
    status: 'ON-SITE',
    specializations: ['Trauma Care', 'Mobile Field Clinic', 'Water-borne Epidemics'],
    phone: '+91 98250 90003',
    contactPoc: 'Dr. Rajesh Shah'
  },
  {
    id: 'ngo-goonj-04',
    name: 'Goonj Rapid Humanitarian Wing',
    focus: 'Food, Clean Water & Essential Clothing Supplies',
    contact: '+91 98250 90004',
    headquartersPoc: 'Pooja Iyer (Supply Coordinator)',
    activeVolunteers: 80,
    assignedMissionsCount: 1,
    operationalZones: ['Chandkheda', 'Maninagar', 'Vatva'],
    headquartersZone: 'Maninagar Relief Depot',
    activeSquads: 10,
    status: 'ACTIVE',
    specializations: ['Dry Rations', 'Blankets & Tarpaulins', 'Clean Drinking Water'],
    phone: '+91 98250 90004',
    contactPoc: 'Pooja Iyer'
  },
  {
    id: 'ngo-rotary-05',
    name: 'Rotary Disaster Relief Network',
    focus: 'Potable Water Tankers & Safe Shelter Logistics',
    contact: '+91 98250 90005',
    headquartersPoc: 'Sanjay Trivedi (Logistics Lead)',
    activeVolunteers: 35,
    assignedMissionsCount: 0,
    operationalZones: ['Bopal', 'Satellite', 'Sarkhej'],
    headquartersZone: 'Bopal Logistics Hub',
    activeSquads: 5,
    status: 'STANDBY',
    specializations: ['Water Tankers', 'Temporary Shelters', 'Solar Lanterns'],
    phone: '+91 98250 90005',
    contactPoc: 'Sanjay Trivedi'
  }
];

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'res-amb-02',
    name: 'Ambulance 02',
    type: 'ambulance',
    status: 'DEPLOYED',
    latitude: 23.0130,
    longitude: 72.5625,
    locationZone: 'Zone B (Paldi)',
    capacity: 2,
    contact: '+91 98250 90002',
    assignedIncidentId: '104',
    updatedTime: '14:38',
  },
  {
    id: 'res-rescue-04',
    name: 'Rescue Team 4 (NDRF Boat)',
    type: 'rescue_team',
    status: 'DEPLOYED',
    latitude: 23.0120,
    longitude: 72.5615,
    locationZone: 'Zone B (Paldi)',
    capacity: 12,
    contact: '+91 98250 90004',
    assignedIncidentId: '104',
    updatedTime: '14:38',
  },
  {
    id: 'res-fire-03',
    name: 'Fire Unit 03 (High Capacity Pump)',
    type: 'fire_unit',
    status: 'ASSIGNED',
    latitude: 23.0440,
    longitude: 72.5770,
    locationZone: 'Zone C (Usmanpura)',
    capacity: 6,
    contact: '+91 98250 90003',
    assignedIncidentId: '105',
    updatedTime: '14:30',
  },
  {
    id: 'res-rescue-01',
    name: 'Rescue Team 01 (NDRF Urban Search)',
    type: 'rescue_team',
    status: 'ASSIGNED',
    latitude: 23.0190,
    longitude: 72.5695,
    locationZone: 'Zone A (Ellis Bridge)',
    capacity: 10,
    contact: '+91 98250 90001',
    assignedIncidentId: '106',
    updatedTime: '14:44',
  },
  {
    id: 'res-fire-01',
    name: 'Fire Unit 01 (Chemical/Hazmat)',
    type: 'fire_unit',
    status: 'ASSIGNED',
    latitude: 23.0350,
    longitude: 72.5580,
    locationZone: 'Zone B (Navrangpura)',
    capacity: 6,
    contact: '+91 98250 90011',
    assignedIncidentId: '107',
    updatedTime: '14:28',
  },
  {
    id: 'res-police-01',
    name: 'Police Rapid Unit 01',
    type: 'police',
    status: 'ASSIGNED',
    latitude: 23.0600,
    longitude: 72.5670,
    locationZone: 'Zone C (Akhbarnagar)',
    capacity: 4,
    contact: '+91 98250 90021',
    assignedIncidentId: '108',
    updatedTime: '14:22',
  },
  {
    id: 'res-rescue-02',
    name: 'Rescue Team 02 (SDRF Boat Unit)',
    type: 'rescue_team',
    status: 'DEPLOYED',
    latitude: 23.1095,
    longitude: 72.5845,
    locationZone: 'Zone D (Chandkheda)',
    capacity: 10,
    contact: '+91 98250 90012',
    assignedIncidentId: '111',
    updatedTime: '14:15',
  },
  {
    id: 'res-amb-01',
    name: 'Ambulance 01 (Advanced Life Support)',
    type: 'ambulance',
    status: 'DEPLOYED',
    latitude: 23.1085,
    longitude: 72.5855,
    locationZone: 'Zone D (Chandkheda)',
    capacity: 2,
    contact: '+91 98250 90031',
    assignedIncidentId: '111',
    updatedTime: '14:15',
  },
  {
    id: 'res-amb-03',
    name: 'Ambulance 03 (Basic)',
    type: 'ambulance',
    status: 'AVAILABLE',
    latitude: 23.0390,
    longitude: 72.5610,
    locationZone: 'Zone A (Civil Base)',
    capacity: 2,
    contact: '+91 98250 90033',
    updatedTime: '14:00',
  },
  {
    id: 'res-rescue-03',
    name: 'Rescue Team 03 (Civil Defence Volunteers)',
    type: 'rescue_team',
    status: 'AVAILABLE',
    latitude: 23.0480,
    longitude: 72.5810,
    locationZone: 'Zone B (Riverfront Station)',
    capacity: 15,
    contact: '+91 98250 90043',
    updatedTime: '14:00',
  },
  {
    id: 'res-fire-02',
    name: 'Fire Unit 02 (Standard Tender)',
    type: 'fire_unit',
    status: 'AVAILABLE',
    latitude: 23.0280,
    longitude: 72.5720,
    locationZone: 'Zone A (Central Fire Stn)',
    capacity: 6,
    contact: '+91 98250 90052',
    updatedTime: '13:50',
  },
  {
    id: 'res-med-04',
    name: 'Medical Corps Team 04 (Triage)',
    type: 'medical_team',
    status: 'AVAILABLE',
    latitude: 23.0150,
    longitude: 72.5690,
    locationZone: 'Zone B (SVP Hospital Depot)',
    capacity: 8,
    contact: '+91 98250 90064',
    updatedTime: '14:10',
  },
  {
    id: 'res-sup-01',
    name: 'Ration & Clean Water Truck 01',
    type: 'supplies',
    status: 'AVAILABLE',
    latitude: 23.0500,
    longitude: 72.5900,
    locationZone: 'Zone C (Relief Central)',
    capacity: 500,
    contact: '+91 98250 90071',
    updatedTime: '13:45',
  },
  {
    id: 'res-pol-02',
    name: 'Police Traffic Evacuation Squad 02',
    type: 'police',
    status: 'AVAILABLE',
    latitude: 23.0320,
    longitude: 72.5650,
    locationZone: 'Zone B (Navrangpura)',
    capacity: 6,
    contact: '+91 98250 90082',
    updatedTime: '14:05',
  },
];

export const SUPPORTED_CITIES: CityInfo[] = [
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    center: [23.0225, 72.5714],
    zoom: 13,
    localities: [
      { name: 'Paldi', latitude: 23.0145, longitude: 72.5640, zone: 'West Zone' },
      { name: 'Navrangpura', latitude: 23.0395, longitude: 72.5620, zone: 'West Zone' },
      { name: 'Usmanpura', latitude: 23.0450, longitude: 72.5710, zone: 'Central Zone' },
      { name: 'Riverfront Corridor', latitude: 23.0300, longitude: 72.5720, zone: 'Central Zone' },
      { name: 'Maninagar', latitude: 22.9970, longitude: 72.6030, zone: 'South Zone' },
      { name: 'Chandkheda', latitude: 23.1120, longitude: 72.5860, zone: 'North Zone' },
      { name: 'Bopal', latitude: 23.0340, longitude: 72.4680, zone: 'South-West Zone' },
      { name: 'Satellite', latitude: 23.0270, longitude: 72.5270, zone: 'West Zone' },
      { name: 'Sarkhej', latitude: 22.9800, longitude: 72.5000, zone: 'South-West Zone' },
    ],
  },
  {
    id: 'surat',
    name: 'Surat',
    state: 'Gujarat',
    center: [21.1702, 72.8311],
    zoom: 13,
    localities: [
      { name: 'Adajan', latitude: 21.1960, longitude: 72.7930, zone: 'West Zone' },
      { name: 'Rander', latitude: 21.2180, longitude: 72.7960, zone: 'West Zone' },
      { name: 'Varachha', latitude: 21.2210, longitude: 72.8550, zone: 'East Zone' },
      { name: 'Katargam', latitude: 21.2300, longitude: 72.8250, zone: 'North Zone' },
      { name: 'Athwa Lines', latitude: 21.1730, longitude: 72.8020, zone: 'South-West Zone' },
      { name: 'Piplod', latitude: 21.1550, longitude: 72.7750, zone: 'South-West Zone' },
    ],
  },
  {
    id: 'vadodara',
    name: 'Vadodara',
    state: 'Gujarat',
    center: [22.3072, 73.1812],
    zoom: 13,
    localities: [
      { name: 'Alkapuri', latitude: 22.3120, longitude: 73.1750, zone: 'West Zone' },
      { name: 'Sayajigunj', latitude: 22.3100, longitude: 73.1890, zone: 'Central Zone' },
      { name: 'Manjalpur', latitude: 22.2690, longitude: 73.1950, zone: 'South Zone' },
      { name: 'Karelibaug', latitude: 22.3270, longitude: 73.2050, zone: 'North Zone' },
      { name: 'Gotri', latitude: 22.3150, longitude: 73.1480, zone: 'West Zone' },
    ],
  },
  {
    id: 'rajkot',
    name: 'Rajkot',
    state: 'Gujarat',
    center: [22.3039, 70.8022],
    zoom: 13,
    localities: [
      { name: 'Kalawad Road', latitude: 22.2850, longitude: 70.7680, zone: 'West Zone' },
      { name: 'Yagnik Road', latitude: 22.2980, longitude: 70.7950, zone: 'Central Zone' },
      { name: 'University Road', latitude: 22.2910, longitude: 70.7580, zone: 'West Zone' },
      { name: 'Bhaktinagar', latitude: 22.2750, longitude: 70.8120, zone: 'South Zone' },
    ],
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    center: [19.0760, 72.8777],
    zoom: 12,
    localities: [
      { name: 'Dadar', latitude: 19.0178, longitude: 72.8478, zone: 'Central Zone' },
      { name: 'Bandra', latitude: 19.0596, longitude: 72.8295, zone: 'Western Suburbs' },
      { name: 'Andheri', latitude: 19.1136, longitude: 72.8697, zone: 'Western Suburbs' },
      { name: 'Kurla', latitude: 19.0726, longitude: 72.8845, zone: 'Eastern Suburbs' },
      { name: 'Colaba', latitude: 18.9067, longitude: 72.8147, zone: 'South Mumbai' },
      { name: 'Borivali', latitude: 19.2307, longitude: 72.8567, zone: 'Northern Suburbs' },
    ],
  },
  {
    id: 'delhi',
    name: 'Delhi NCR',
    state: 'Delhi',
    center: [28.6139, 77.2090],
    zoom: 12,
    localities: [
      { name: 'Connaught Place', latitude: 28.6315, longitude: 77.2167, zone: 'Central' },
      { name: 'Karol Bagh', latitude: 28.6520, longitude: 77.1900, zone: 'Central-West' },
      { name: 'Rohini', latitude: 28.7160, longitude: 77.1180, zone: 'North-West' },
      { name: 'Saket', latitude: 28.5244, longitude: 77.2167, zone: 'South' },
      { name: 'Mayur Vihar', latitude: 28.6090, longitude: 77.2990, zone: 'East' },
      { name: 'Dwarka', latitude: 28.5921, longitude: 77.0460, zone: 'South-West' },
    ],
  },
];

export const LOCALITY_EVIDENCE_MAP: Record<string, { local: string; remote: string }> = {
  'Paldi': {
    local: '/images/evidence/paldi.jpg',
    remote: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
  },
  'Maninagar': {
    local: '/images/evidence/maninagar.jpg',
    remote: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&w=800&q=80',
  },
  'Navrangpura': {
    local: '/images/evidence/navrangpura.jpg',
    remote: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=800&q=80',
  },
  'Usmanpura': {
    local: '/images/evidence/usmanpura.jpg',
    remote: 'https://images.unsplash.com/photo-1545063914-a1a6ec821c88?auto=format&fit=crop&w=800&q=80',
  },
  'Riverfront Corridor': {
    local: '/images/evidence/riverfront.jpg',
    remote: 'https://images.unsplash.com/photo-1545063914-a1a6ec821c88?auto=format&fit=crop&w=800&q=80',
  },
  'Chandkheda': {
    local: '/images/evidence/chandkheda.jpg',
    remote: 'https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?auto=format&fit=crop&w=800&q=80',
  },
  'Satellite': {
    local: '/images/evidence/satellite.jpg',
    remote: 'https://images.unsplash.com/photo-1569163139599-0f4517e36f51?auto=format&fit=crop&w=800&q=80',
  },
  'Bopal': {
    local: '/images/evidence/bopal.jpg',
    remote: 'https://images.unsplash.com/photo-1514632595-4944383f2737?auto=format&fit=crop&w=800&q=80',
  },
  'Sarkhej': {
    local: '/images/evidence/sarkhej.jpg',
    remote: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
  },
  'Adajan': {
    local: '/images/evidence/surat.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Rander': {
    local: '/images/evidence/surat.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Varachha': {
    local: '/images/evidence/surat.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Katargam': {
    local: '/images/evidence/surat.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Surat': {
    local: '/images/evidence/surat.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Alkapuri': {
    local: '/images/evidence/vadodara.jpg',
    remote: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
  },
  'Sayajigunj': {
    local: '/images/evidence/vadodara.jpg',
    remote: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
  },
  'Vadodara': {
    local: '/images/evidence/vadodara.jpg',
    remote: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
  },
  'Kalawad Road': {
    local: '/images/evidence/rajkot.jpg',
    remote: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
  },
  'Rajkot': {
    local: '/images/evidence/rajkot.jpg',
    remote: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
  },
  'Mumbai': {
    local: '/images/evidence/mumbai.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Dadar': {
    local: '/images/evidence/mumbai.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Bandra': {
    local: '/images/evidence/mumbai.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Andheri': {
    local: '/images/evidence/mumbai.jpg',
    remote: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?auto=format&fit=crop&w=800&q=80',
  },
  'Delhi NCR': {
    local: '/images/evidence/chandkheda.jpg',
    remote: 'https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?auto=format&fit=crop&w=800&q=80',
  },
  'Connaught Place': {
    local: '/images/evidence/chandkheda.jpg',
    remote: 'https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?auto=format&fit=crop&w=800&q=80',
  },
  'default': {
    local: '/images/evidence/default.jpg',
    remote: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
  },
};

export const getLocalityEvidenceImage = (localityName?: string, cityName?: string): string => {
  if (localityName && LOCALITY_EVIDENCE_MAP[localityName]) {
    return LOCALITY_EVIDENCE_MAP[localityName].local;
  }
  if (cityName && LOCALITY_EVIDENCE_MAP[cityName]) {
    return LOCALITY_EVIDENCE_MAP[cityName].local;
  }
  return '/images/evidence/default.jpg';
};

export const getLocalityFallbackImage = (localityName?: string, cityName?: string): string => {
  if (localityName && LOCALITY_EVIDENCE_MAP[localityName]) {
    return LOCALITY_EVIDENCE_MAP[localityName].remote;
  }
  if (cityName && LOCALITY_EVIDENCE_MAP[cityName]) {
    return LOCALITY_EVIDENCE_MAP[cityName].remote;
  }
  return 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80';
};

export const INITIAL_SHELTERS: Shelter[] = [
  // Ahmedabad Shelters
  {
    id: 'sh-01',
    name: 'Sardar Patel Stadium Indoor Relief Center',
    locationName: 'Navrangpura, Ahmedabad',
    city: 'Ahmedabad',
    locality: 'Navrangpura',
    latitude: 23.0395,
    longitude: 72.5620,
    capacity: 500,
    currentOccupancy: 310,
    contact: '+91 79 2640 1101',
    status: 'OPEN',
    suppliesAvailable: ['Clean Drinking Water', 'Dry Rations', 'Medical First-Aid', 'Blankets', 'Power Backup'],
  },
  {
    id: 'sh-02',
    name: 'Paldi Community Relief Hall',
    locationName: 'Paldi Crossroad, Ahmedabad',
    city: 'Ahmedabad',
    locality: 'Paldi',
    latitude: 23.0145,
    longitude: 72.5640,
    capacity: 250,
    currentOccupancy: 238,
    contact: '+91 79 2657 2202',
    status: 'OPEN',
    suppliesAvailable: ['Drinking Water', 'Hot Food', 'Doctor on duty', 'Emergency Lighting'],
  },
  {
    id: 'sh-03',
    name: 'Chandkheda Municipal School Camp',
    locationName: 'Chandkheda High School, Ahmedabad',
    city: 'Ahmedabad',
    locality: 'Chandkheda',
    latitude: 23.1120,
    longitude: 72.5860,
    capacity: 300,
    currentOccupancy: 180,
    contact: '+91 79 2750 3303',
    status: 'OPEN',
    suppliesAvailable: ['Drinking Water', 'Infant Formula', 'Bedding', 'Mobile Charging'],
  },
  {
    id: 'sh-04',
    name: 'Maninagar Sports Complex Shelter',
    locationName: 'Maninagar East, Ahmedabad',
    city: 'Ahmedabad',
    locality: 'Maninagar',
    latitude: 22.9970,
    longitude: 72.6030,
    capacity: 400,
    currentOccupancy: 395,
    contact: '+91 79 2546 4404',
    status: 'FULL',
    suppliesAvailable: ['Rations Exhausted', 'Medical Wing Operational'],
  },
  {
    id: 'sh-05',
    name: 'Usmanpura Riverfront Relief Pavilion',
    locationName: 'Usmanpura Garden Complex, Ahmedabad',
    city: 'Ahmedabad',
    locality: 'Usmanpura',
    latitude: 23.0450,
    longitude: 72.5710,
    capacity: 350,
    currentOccupancy: 120,
    contact: '+91 79 2755 5505',
    status: 'OPEN',
    suppliesAvailable: ['Clean Water', 'Blankets', 'Hot Meals', 'Sanitation Kits'],
  },
  {
    id: 'sh-06',
    name: 'Satellite Community Center & High Ground Shelter',
    locationName: 'Prernatirth Derasar Road, Satellite, Ahmedabad',
    city: 'Ahmedabad',
    locality: 'Satellite',
    latitude: 23.0270,
    longitude: 72.5270,
    capacity: 280,
    currentOccupancy: 85,
    contact: '+91 79 2676 8812',
    status: 'OPEN',
    suppliesAvailable: ['Clean Water', 'Medical Aid', 'Generators', 'Warm Meals'],
  },
  {
    id: 'sh-07',
    name: 'Bopal Government Primary School Evacuation Shelter',
    locationName: 'South Bopal Ring Road, Ahmedabad',
    city: 'Ahmedabad',
    locality: 'Bopal',
    latitude: 23.0340,
    longitude: 72.4680,
    capacity: 220,
    currentOccupancy: 45,
    contact: '+91 79 2970 4410',
    status: 'OPEN',
    suppliesAvailable: ['Packaged Food', 'Potable Water', 'Baby Care Kits'],
  },

  // Surat Shelters
  {
    id: 'sh-su-01',
    name: 'Adajan Indoor Stadium Relief Hub',
    locationName: 'Anand Mahal Road, Adajan, Surat',
    city: 'Surat',
    locality: 'Adajan',
    latitude: 21.1960,
    longitude: 72.7930,
    capacity: 600,
    currentOccupancy: 210,
    contact: '+91 261 278 1100',
    status: 'OPEN',
    suppliesAvailable: ['Drinking Water', 'Food Packets', 'First-Aid', 'Rescue Boat Base'],
  },
  {
    id: 'sh-su-02',
    name: 'Rander Municipal High School Safe Haven',
    locationName: 'Gorat Road, Rander, Surat',
    city: 'Surat',
    locality: 'Rander',
    latitude: 21.2180,
    longitude: 72.7960,
    capacity: 350,
    currentOccupancy: 190,
    contact: '+91 261 279 2211',
    status: 'OPEN',
    suppliesAvailable: ['Water Purifiers', 'Warm Clothing', 'Doctors on standby'],
  },
  {
    id: 'sh-su-03',
    name: 'Varachha Community Hall Shelter',
    locationName: 'Mini Bazar, Varachha, Surat',
    city: 'Surat',
    locality: 'Varachha',
    latitude: 21.2210,
    longitude: 72.8550,
    capacity: 400,
    currentOccupancy: 310,
    contact: '+91 261 254 3322',
    status: 'OPEN',
    suppliesAvailable: ['Dry Rations', 'Clean Water', 'ORS Kits'],
  },

  // Vadodara Shelters
  {
    id: 'sh-brc-01',
    name: 'Alkapuri Municipal Welfare Center',
    locationName: 'RC Dutt Road, Alkapuri, Vadodara',
    city: 'Vadodara',
    locality: 'Alkapuri',
    latitude: 22.3120,
    longitude: 73.1750,
    capacity: 320,
    currentOccupancy: 95,
    contact: '+91 265 233 4401',
    status: 'OPEN',
    suppliesAvailable: ['Potable Water', 'Emergency Meals', 'Triage Station'],
  },
  {
    id: 'sh-brc-02',
    name: 'Sayajigunj Relief Base & Camp',
    locationName: 'Station Road, Sayajigunj, Vadodara',
    city: 'Vadodara',
    locality: 'Sayajigunj',
    latitude: 22.3100,
    longitude: 73.1890,
    capacity: 450,
    currentOccupancy: 280,
    contact: '+91 265 236 5512',
    status: 'OPEN',
    suppliesAvailable: ['Packaged Rations', 'Water Bottles', 'Blankets', 'Power Outlets'],
  },

  // Mumbai Shelters
  {
    id: 'sh-mum-01',
    name: 'Dadar BMC Relief Complex',
    locationName: 'Dr. Babasaheb Ambedkar Road, Dadar, Mumbai',
    city: 'Mumbai',
    locality: 'Dadar',
    latitude: 19.0178,
    longitude: 72.8478,
    capacity: 550,
    currentOccupancy: 320,
    contact: '+91 22 2414 7788',
    status: 'OPEN',
    suppliesAvailable: ['Clean Water', 'Food Distribution', 'Medical Staff', 'High Ground'],
  },
  {
    id: 'sh-mum-02',
    name: 'Bandra Kurla Evacuation Hall',
    locationName: 'BKC Central Avenue, Bandra, Mumbai',
    city: 'Mumbai',
    locality: 'Bandra',
    latitude: 19.0596,
    longitude: 72.8295,
    capacity: 400,
    currentOccupancy: 150,
    contact: '+91 22 2659 1122',
    status: 'OPEN',
    suppliesAvailable: ['Emergency Beds', 'Hot Food', 'Doctor Station'],
  },

  // Delhi NCR Shelters
  {
    id: 'sh-del-01',
    name: 'Connaught Place Civic Center Shelter',
    locationName: 'Barakhamba Road, Connaught Place, New Delhi',
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    latitude: 28.6315,
    longitude: 77.2167,
    capacity: 500,
    currentOccupancy: 140,
    contact: '+91 11 2334 5678',
    status: 'OPEN',
    suppliesAvailable: ['Water Tankers', 'Packed Meals', 'Ambulance On Standby'],
  },
  {
    id: 'sh-del-02',
    name: 'Rohini District Sports Complex Relief Facility',
    locationName: 'Sector 14, Rohini, New Delhi',
    city: 'Delhi NCR',
    locality: 'Rohini',
    latitude: 28.7160,
    longitude: 77.1180,
    capacity: 650,
    currentOccupancy: 210,
    contact: '+91 11 2755 8899',
    status: 'OPEN',
    suppliesAvailable: ['Clean Drinking Water', 'Dry Rations', 'Sanitary Packs', 'Mobile Charging'],
  },
];

export const INITIAL_EMERGENCY_HELPS: EmergencyHelp[] = [
  // Ahmedabad - Paldi
  {
    id: 'help-ah-01',
    name: 'Ahmedabad Disaster Control Room (24x7)',
    category: 'helpline',
    city: 'Ahmedabad',
    locality: 'Paldi',
    address: 'AMC Central Emergency Operations Center, Paldi Crossroad',
    phone: '112 / +91 79 2539 1811',
    operationalHours: '24 Hours Open',
    details: 'Direct dispatch for NDRF boat units, fire rescue, and municipal flood pumping squads.',
    latitude: 23.0145,
    longitude: 72.5640,
  },
  {
    id: 'help-ah-02',
    name: 'Sardar Vallabhbhai Patel (SVP) Institute of Medical Sciences & Trauma',
    category: 'medical',
    city: 'Ahmedabad',
    locality: 'Paldi',
    address: 'Ellis Bridge / Paldi Riverfront, Ahmedabad',
    phone: '+91 79 2657 7621',
    operationalHours: '24 Hours Emergency & Trauma',
    details: '1500-bed super-specialty hospital with dedicated flood trauma unit, blood bank, and emergency ICU.',
    latitude: 23.0180,
    longitude: 72.5680,
  },
  {
    id: 'help-ah-03',
    name: 'Paldi AMC Potable Water Tanker Depot & Ration Point',
    category: 'food_water',
    city: 'Ahmedabad',
    locality: 'Paldi',
    address: 'Near Mahalaxmi Crossroad, Paldi, Ahmedabad',
    phone: '+91 79 2657 9901',
    operationalHours: '06:00 AM - 10:00 PM',
    details: 'Free distribution of 20L clean water containers, chlorine purification tablets, and emergency dry food packets.',
    latitude: 23.0110,
    longitude: 72.5610,
  },
  {
    id: 'help-ah-04',
    name: 'Sanskar Kendra Elevated Assembly Ground',
    category: 'assembly_point',
    city: 'Ahmedabad',
    locality: 'Paldi',
    address: 'Tagore Memorial Hall Compound, Paldi',
    phone: '+91 79 2657 3344',
    operationalHours: '24 Hours Safe Refuge',
    details: 'High-elevation municipal plaza designated for citizen assembly, helicopter air-drop drops, and bus shuttles.',
    latitude: 23.0130,
    longitude: 72.5695,
  },

  // Ahmedabad - Navrangpura
  {
    id: 'help-ah-05',
    name: 'Navrangpura Civic Emergency Ward Office',
    category: 'helpline',
    city: 'Ahmedabad',
    locality: 'Navrangpura',
    address: 'Opp. Navrangpura Bus Stand, CG Road',
    phone: '+91 79 2644 1212',
    operationalHours: '24 Hours Active',
    details: 'Ward emergency desk handling local street clearing, fallen tree removals, and electricity restoration.',
    latitude: 23.0375,
    longitude: 72.5605,
  },
  {
    id: 'help-ah-06',
    name: 'Civil Hospital Satellite First-Aid & Triage Depot',
    category: 'medical',
    city: 'Ahmedabad',
    locality: 'Navrangpura',
    address: 'Commerce Six Roads, Navrangpura',
    phone: '+91 79 2642 8844',
    operationalHours: '24 Hours Emergency',
    details: 'Rapid triage outpost with on-call doctors, tetanus injections, burn treatment, and ALS ambulance bay.',
    latitude: 23.0385,
    longitude: 72.5560,
  },
  {
    id: 'help-ah-07',
    name: 'Gujarat University Convention Ground Evacuation Point',
    category: 'assembly_point',
    city: 'Ahmedabad',
    locality: 'Navrangpura',
    address: 'Helmet Circle, Navrangpura',
    phone: '+91 79 2630 1155',
    operationalHours: '24 Hours Safe Refuge',
    details: 'Elevated multi-acre ground capable of housing up to 2,000 citizens with immediate transport links.',
    latitude: 23.0410,
    longitude: 72.5480,
  },
  {
    id: 'help-ah-08',
    name: 'Navrangpura NGO Community Kitchen & Water Distribution',
    category: 'food_water',
    city: 'Ahmedabad',
    locality: 'Navrangpura',
    address: 'Mithakhali Six Roads, Navrangpura',
    phone: '+91 98251 44556',
    operationalHours: '07:00 AM - 09:00 PM',
    details: 'Provides hot meals, infant porridge, and bottled mineral water for citizens evacuated from waterlogged homes.',
    latitude: 23.0330,
    longitude: 72.5635,
  },

  // Ahmedabad - Usmanpura
  {
    id: 'help-ah-09',
    name: 'Usmanpura River Flood Action Post',
    category: 'helpline',
    city: 'Ahmedabad',
    locality: 'Usmanpura',
    address: 'Riverfront West Promenade, Usmanpura',
    phone: '+91 79 2755 1010',
    operationalHours: '24 Hours Active',
    details: 'Monitors river crest levels and dispatches amphibious evacuation crafts.',
    latitude: 23.0460,
    longitude: 72.5730,
  },
  {
    id: 'help-ah-10',
    name: 'Riverfront Elevated Gardens Assembly Ground',
    category: 'assembly_point',
    city: 'Ahmedabad',
    locality: 'Usmanpura',
    address: 'Sabarmati Riverfront Promenade, Usmanpura Section',
    phone: '+91 79 2755 2020',
    operationalHours: '24 Hours Open',
    details: 'Flood-safe upper promenade level equipped with solar floodlights and citizen evacuation shelter.',
    latitude: 23.0440,
    longitude: 72.5700,
  },

  // Surat - Adajan
  {
    id: 'help-su-01',
    name: 'Surat Municipal Corporation Flood Helpline',
    category: 'helpline',
    city: 'Surat',
    locality: 'Adajan',
    address: 'SMC West Zone Office, Pal-Adajan Road',
    phone: '+91 261 278 2222',
    operationalHours: '24 Hours Active',
    details: 'SMC 24x7 control room coordinating Tapi river flood relief and water pumping units.',
    latitude: 21.1980,
    longitude: 72.7950,
  },
  {
    id: 'help-su-02',
    name: 'Adajan Sanjivani Trauma & Multispecialty Hospital',
    category: 'medical',
    city: 'Surat',
    locality: 'Adajan',
    address: 'LP Savani Road, Adajan, Surat',
    phone: '+91 261 278 7700',
    operationalHours: '24 Hours Open',
    details: 'Emergency triage with dedicated pediatric and respiratory support units.',
    latitude: 21.1940,
    longitude: 72.7910,
  },
  {
    id: 'help-su-03',
    name: 'Tapi Relief Drinking Water Point',
    category: 'food_water',
    city: 'Surat',
    locality: 'Adajan',
    address: 'Adajan Gam Circle, Surat',
    phone: '+91 261 278 9988',
    operationalHours: '06:00 AM - 10:00 PM',
    details: 'Clean drinking water tankers and pre-packaged family ration kits.',
    latitude: 21.1970,
    longitude: 72.7980,
  },

  // Vadodara - Alkapuri
  {
    id: 'help-vd-01',
    name: 'Vadodara Central Emergency Helpline',
    category: 'helpline',
    city: 'Vadodara',
    locality: 'Alkapuri',
    address: 'VMC Disaster Cell, Alkapuri Road',
    phone: '+91 265 242 2222',
    operationalHours: '24 Hours Active',
    details: 'Vishwamitri river monitoring control center and rescue dispatch squad.',
    latitude: 22.3130,
    longitude: 73.1760,
  },
  {
    id: 'help-vd-02',
    name: 'SSG Hospital Satellite Emergency Wing',
    category: 'medical',
    city: 'Vadodara',
    locality: 'Alkapuri',
    address: 'Jetalpur Road, Alkapuri, Vadodara',
    phone: '+91 265 233 1199',
    operationalHours: '24 Hours Open',
    details: '24/7 disaster trauma care, snake bite antivenom depot, and critical care units.',
    latitude: 22.3110,
    longitude: 73.1740,
  },

  // Mumbai - Dadar
  {
    id: 'help-mum-01',
    name: 'BMC Disaster Management Control Room',
    category: 'helpline',
    city: 'Mumbai',
    locality: 'Dadar',
    address: 'BMC G-North Ward Office, Dadar West',
    phone: '1916 / +91 22 2430 4000',
    operationalHours: '24 Hours Active',
    details: 'Municipal control desk providing real-time pumping status, high tide alerts, and rescue coordinates.',
    latitude: 19.0190,
    longitude: 72.8450,
  },
  {
    id: 'help-mum-02',
    name: 'KEM Hospital Disaster Emergency Care',
    category: 'medical',
    city: 'Mumbai',
    locality: 'Dadar',
    address: 'Acharya Donde Marg, Parel / Dadar',
    phone: '+91 22 2410 7000',
    operationalHours: '24 Hours Emergency',
    details: 'Level-1 trauma center equipped with mass casualty disaster response protocols.',
    latitude: 19.0020,
    longitude: 72.8420,
  },
  {
    id: 'help-mum-03',
    name: 'Shivaji Park High Ground Assembly Area',
    category: 'assembly_point',
    city: 'Mumbai',
    locality: 'Dadar',
    address: 'Shivaji Park Ground, Dadar West',
    phone: '+91 22 2445 1200',
    operationalHours: '24 Hours Safe Refuge',
    details: 'Safe open high-ground assembly for coastal flood evacuation and relief transport base.',
    latitude: 19.0270,
    longitude: 72.8380,
  },

  // Delhi NCR - Connaught Place
  {
    id: 'help-del-01',
    name: 'Delhi State Disaster Management Authority (DDMA) Control',
    category: 'helpline',
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    address: 'Palika Kendra, Sansad Marg, New Delhi',
    phone: '1077 / +91 11 2341 8000',
    operationalHours: '24 Hours Active',
    details: 'Central coordination for NDRF battalions, civil defence corps, and quick response teams.',
    latitude: 28.6280,
    longitude: 77.2140,
  },
  {
    id: 'help-del-02',
    name: 'Dr. Ram Manohar Lohia Hospital Emergency & Trauma',
    category: 'medical',
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    address: 'Baba Kharak Singh Marg, Connaught Place',
    phone: '+91 11 2336 5525',
    operationalHours: '24 Hours Open',
    details: 'Apex central government emergency hospital with dedicated disaster resuscitation wards.',
    latitude: 28.6240,
    longitude: 77.2030,
  },
];

export const INITIAL_ALERTS: EmergencyAlert[] = [
  {
    id: 'ALT-101',
    title: 'OFFICIAL EMERGENCY ALERT — FLOOD WARNING',
    message: 'Sabarmati river discharge exceeds safe threshold. Avoid low-lying riverfront roads and subterranean parking in Paldi and Usmanpura. Move to designated shelters if instructed.',
    disasterType: 'Flood',
    severity: 'CRITICAL',
    geographicArea: 'Ahmedabad Central & Riverfront Corridor (5km radius)',
    instructions: '1. Do not drive through flooded underpasses\n2. Turn off primary electrical mains if water enters house\n3. Call 112 or use Disaster Intelligence 1-touch SOS for boat extraction',
    issuedBy: 'Riya Sharma, District Disaster Authority',
    issuedAt: '14:35',
    expiresAt: '20:00',
    status: 'ACTIVE',
  },
  {
    id: 'ALT-102',
    title: 'OFFICIAL WEATHER ALERT — EXTREME PRECIPITATION WATCH',
    message: 'Severe thunderstorms with cloud burst potential projected over Ahmedabad district for the next 4 hours. Stay indoors away from electrical installations.',
    disasterType: 'Flood',
    severity: 'HIGH',
    geographicArea: 'Ahmedabad District & Northern Gandhinagar Boundary',
    instructions: 'Keep emergency supplies and charged phones ready. Report trapped citizens via Community Report.',
    issuedBy: 'State Disaster Management Authority (GSDMA)',
    issuedAt: '13:00',
    expiresAt: '22:00',
    status: 'ACTIVE',
  },
];

export const INITIAL_DATA_SOURCES: ExternalDataSource[] = [
  {
    id: 'src-weather',
    name: 'Weather Feed (IMD / Open-Meteo)',
    sourceType: 'Weather Feed',
    endpoint: 'https://api.open-meteo.com/v1/forecast?latitude=23.0225&longitude=72.5714',
    status: 'ONLINE',
    lastSuccessfulSync: '14:58 (2m ago)',
    message: 'Precipitation rate: 42mm/h; wind gust: 38km/h. Doppler radar connected.',
    itemsSyncedCount: 144,
  },
  {
    id: 'src-disaster',
    name: 'Disaster Feed (GDACS & USGS)',
    sourceType: 'Disaster Feed',
    endpoint: 'https://www.gdacs.org/xml/rss.xml',
    status: 'ONLINE',
    lastSuccessfulSync: '14:55 (5m ago)',
    message: 'Alert level ORANGE: Indian Western Seaboard Cyclone & Monsoon Depression.',
    itemsSyncedCount: 28,
  },
  {
    id: 'src-gov',
    name: 'Government Feed (NDMA / GSDMA)',
    sourceType: 'Government Feed',
    endpoint: 'https://ndma.gov.in/api/v1/feed/ahmedabad',
    status: 'DEGRADED',
    lastSuccessfulSync: '14:32 (28m ago)',
    message: 'Server latency elevated (timeout > 4500ms). Core operations running uninterrupted on cached telemetry.',
    itemsSyncedCount: 8,
  },
  {
    id: 'src-citizen',
    name: 'Citizen Ingestion Stream',
    sourceType: 'Citizen Reports',
    endpoint: 'internal://websocket/citizen-reports',
    status: 'ONLINE',
    lastSuccessfulSync: '14:59 (just now)',
    message: 'Web & mobile ingestion channel active with verified municipal locality zoning and coordinate mapping.',
    itemsSyncedCount: 57,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '14:45:10',
    actor: 'Riya Sharma',
    role: 'COORDINATOR',
    action: 'STATUS_UPDATE',
    targetId: 'Incident #104',
    details: 'Status transitioned from ASSIGNED to IN PROGRESS upon Rescue Team 4 arrival.',
  },
  {
    id: 'log-2',
    timestamp: '14:38:22',
    actor: 'Riya Sharma',
    role: 'COORDINATOR',
    action: 'RESOURCE_ASSIGNED',
    targetId: 'Incident #104',
    details: 'Assigned Ambulance 02 and Rescue Team 4 (NDRF Boat).',
  },
  {
    id: 'log-3',
    timestamp: '14:35:05',
    actor: 'Riya Sharma',
    role: 'COORDINATOR',
    action: 'ALERT_PUBLISHED',
    targetId: 'ALT-101',
    details: 'Published official critical flood warning after 3-step coordinator review.',
  },
  {
    id: 'log-4',
    timestamp: '14:34:12',
    actor: 'Riya Sharma',
    role: 'COORDINATOR',
    action: 'INCIDENT_VERIFIED',
    targetId: 'Incident #104',
    details: 'Verified citizen crowdsourced report into official incident #104 (CRITICAL flood).',
  },
];
